### ISSUE TITLE
--playlist transferring every playlist rather than specified playlist 

### ISSUE THREAD

**Issue by Rasinzz** [Hexiro/spotify-to-musi#5] opened 2022-05-11 20:47 UTC
Ok, so I ran the `--playlist` command and it worked great with no errors, but when I imported the recovery code into Musi, it imported every Spotify playlist I had liked rather than just the specified playlist.

**Comment by Hexiro** [comment] 2022-05-11 23:40
yup so right now this is actually intended behavior. There's a flag (`--no-user` or `-nu`) that will prevent this and only transfer the playlist(s). Output of `spotify-to-musi transfer --help`:
![image](https://user-images.githubusercontent.com/42787085/167964538-712c2e61-aac1-4e9c-9abc-bfe473660b0d.png)
Maybe I should change it to be no by default so it's a little more clear when the user's stuff is getting transfered. What do you think? @Rasinzz

**Comment by Rasinzz** [comment] 2022-05-12 02:16
> yup so right now this is actually intended behavior. There's a flag (`--no-user` or `-nu`) that will prevent this and only transfer the playlist(s). Output of `spotify-to-musi transfer --help`: ![image](https://user-images.githubusercontent.com/42787085/167964538-712c2e61-aac1-4e9c-9abc-bfe473660b0d.png) Maybe I should change it to be no by default so it's a little more clear when the user's stuff is getting transfered. What do you think? @Rasinzz

Just did it and it worked. I would just add something to the README specifying it.

Command I used: `spotify-to-musi transfer -nu -pl https://open.spotify.com/playlist/4Sn3ZXM6ULcZ7uG1dXS4gE?si=bc524656f4574496`

**Comment by Rasinzz** [comment] 2022-05-12 03:16
Now that I think about it, just default it to no user likes and allow them to use the arguments if they want

**Comment by Hexiro** [comment] 2022-05-12 19:09
I agree. Will change

**Comment by Hexiro** [comment] 2022-05-15 01:38
@Rasinzz i just pushed a change that so that it now uses the YouTube Music API instead of YouTube itself. This means that YouTube does all the hard work of deciding what videos are songs instead of me needing to try and parse that from results (so it's much better). It's also much much much much much faster. Like from needing 5 threads and still taking minutes to taking seconds. A very simple but positive change. Bugs may linger so please try it out but this looks like a very great change IMO

**Comment by Rasinzz** [comment] 2022-05-15 01:39
> 

Ok, I'll have a look right now.

**Comment by Rasinzz** [comment] 2022-05-15 01:42
@Hexiro Holy! I just tested it on a playlist with 225 songs and it took like 1 second lol. Before it used to take a couple minutes. Great work, boss!

**Comment by Hexiro** [comment] 2022-05-15 01:46
> @Hexiro Holy! I just tested it on a playlist with 225 songs and it took like 1 second lol. Before it used to take a couple minutes. Great work, boss! I'm going to test it on my main playlist so if it encounters any errors I'll let you know.
> 
> **EDIT:** Insane! Just ran it on my main playlist that has 1,238 songs and it finished in like 5 seconds lol.

Honestly, all I did was remove the old lib that searched YouTube itself and dropped in a new lib that searches YouTube music with that just happening to be so much faster. Right now, it's using 5 threads to search at once, but odds are I'm going to remove this to make the code a lot safer, as the speed improvement isn't really needed.

**Comment by Hexiro** [comment] 2022-05-15 01:47
the main benefit I see from this is now using Musi no songs should be clean, or be the music video which sometimes contains extra sounds, as YouTube Music has a large database (i presume) of what YouTube videos are precisely the audio. I also don't know if searching YouTube Music like this will have any rate limits,  so be careful about doing a bunch of songs frequently.

**Comment by Rasinzz** [comment] 2022-05-15 02:12
> the main benefit I see from this is now using Musi no songs should be clean, or be the music video which sometimes contains extra sounds, as YouTube Music has a large database (i presume) of what YouTube videos are precisely the audio. I also don't know if searching YouTube Music like this will have any rate limits, so be careful about doing a bunch of songs frequently.

Ok.

There was also one thing I found. I didn't get any errors but the playlists size's were different when I imported it in Musi.

The first playlist that I converted had 225 songs on Spotify, and on Musi, after conversion, it has 171 songs. I am unsure why this is as there were no "local file" songs in the playlist and all the songs are from pretty well known artists.

Here's the link to the playlist: https://open.spotify.com/playlist/4Sn3ZXM6ULcZ7uG1dXS4gE?si=0e3f1a52a13146f8

**Comment by Hexiro** [comment] 2022-05-15 02:17
> > the main benefit I see from this is now using Musi no songs should be clean, or be the music video which sometimes contains extra sounds, as YouTube Music has a large database (i presume) of what YouTube videos are precisely the audio. I also don't know if searching YouTube Music like this will have any rate limits, so be careful about doing a bunch of songs frequently.
> 
> Ok.
> 
> There was also one thing I found. I didn't get any errors but the playlists size's were different when I imported it in Musi.
> 
> The first playlist that I converted had 225 songs on Spotify, and on Musi, after conversion, it has 171 songs. I am unsure why this is as there were no "local file" songs in the playlist and all the songs are from pretty well known artists.
> 
> Here's the link to the playlist: https://open.spotify.com/playlist/4Sn3ZXM6ULcZ7uG1dXS4gE?si=0e3f1a52a13146f8

yikes that doesn't sound like an easy bug to find. I'll look into this tomorrow. I'll have to see if this change occured because of the new YouTube Music search or if it's been lurking all along.

**Comment by Rasinzz** [comment] 2022-05-15 02:32
@Hexiro Ok, I think it was doing this because I had duplicates in my playlists. I'm going to make a playlist with no duplicates and I'll test it on that.

**Comment by Rasinzz** [comment] 2022-05-15 03:08
> @Hexiro Ok, I think it was doing this because I had duplicates in my playlists. I'm going to make a playlist with no duplicates and I'll test it on that.

Ok, I removed duplicates and it dropped the amount of songs from 225 to 180, but still the script only converts 171 songs in the Musi playlist.

**Comment by Hexiro** [comment] 2022-05-15 03:16
I noticed the same thing, out of my playlists with less than 50 songs none were missing, but all of the ones with like 100-150 like 5-10 would be missing. I'll look into this tomorrow to see if I can figure out what's causing these songs to be skipped.

**Comment by Rasinzz** [comment] 2022-05-15 03:18
> I noticed the same thing, out of my playlists with less than 50 songs none were missing, but all of the ones with like 100-150 like 5-10 would be missing. I'll look into this tomorrow to see if I can figure out what's causing these songs to be skipped.

Yeah, just tested with a playlist that had 15 songs and it converted all 15 songs.

**Comment by Rasinzz** [comment] 2022-05-15 17:20
Also as I'm listening to the playlist on Musi some of the songs are not explicit

**Comment by Hexiro** [comment] 2022-05-15 18:31
> Also as I'm listening to the playlist on Musi some of the songs are not explicit

yeah, i noticed that too. YouTube Music has filters for explicit / non explicit so i'll have to look into prioritizing the explicit filter.

**Comment by Hexiro** [comment] 2022-05-15 19:13
I don't know if I was just too tired to realize this last night or what, but the reason it was so fast is because it was using the cache, probably the same reason the songs weren't explicit. Regardless, I have added a check that makes sure The song will be explicit if possible.

If you're on a Window machine your cache file is located at: `%appdata%/spotify-to-musi/data.cache.json` 
If not, check here to see file locations: https://github.com/Hexiro/spotify-to-musi/blob/76939dd85e874fa1454633708b07f379fd777f9a/spotify_to_musi/paths.py#L9

**Comment by Rasinzz** [comment] 2022-05-15 19:49
> I don't know if I was just too tired to realize this last night or what, but the reason it was so fast is because it was using the cache, probably the same reason the songs weren't explicit. Regardless, I have added a check that makes sure The song will be explicit if possible.
> 
> If you're on a Window machine your cache file is located at: `%appdata%/spotify-to-musi/data.cache.json` If not, check here to see file locations:
> 
> https://github.com/Hexiro/spotify-to-musi/blob/76939dd85e874fa1454633708b07f379fd777f9a/spotify_to_musi/paths.py#L9

Ok

**Comment by Hexiro** [comment] 2022-05-15 22:27
> > I don't know if I was just too tired to realize this last night or what, but the reason it was so fast is because it was using the cache, probably the same reason the songs weren't explicit. Regardless, I have added a check that makes sure The song will be explicit if possible.
> 
> > 
> 
> > If you're on a Window machine your cache file is located at: `%appdata%/spotify-to-musi/data.cache.json` If not, check here to see file locations:
> 
> > 
> 
> > https://github.com/Hexiro/spotify-to-musi/blob/76939dd85e874fa1454633708b07f379fd777f9a/spotify_to_musi/paths.py#L9
> 
> 
> 
> Ok
> 
> 
> 
> **EDIT:** Just ran it on the same playlist from last night that has 180 songs in it and now it converted 176 songs rather than 171.

I checked the code and for each playlist it sends the data to the same number of songs as the original spotify playlist (assuming it can find all the songs) So i'm not sure why some don't convert.

**Comment by Hexiro** [comment] 2022-05-19 21:09
gonna close this since the issue has been solved. If you'd ever like to chat you could always contact me privately, open a discussion in discussions, or open a new issue :)

**Closed by Hexiro** 2022-05-19 21:09 UTC
